### ISSUE TITLE
Use Psalm to analyse WordPress Plugins

### ISSUE THREAD

**Issue by dac514** [muglug/WordPressAnalysis#1]
I'm a PhpStorm user who tries very hard that the right margin has no errors, warnings, or colours of any kind. PhpStorm does static analysis on WordPress plugin code [and it's pretty very smart about it](https://confluence.jetbrains.com/display/PhpStorm/WordPress+Development+using+PhpStorm).

I'm looking at Psalm as a way to analyse WordPress plugins. Not WordPress core. 

It would be useful on a team where not everyone uses PhpStorm. Or those who do but ignore all the errors. Psalm could be part of the CI acceptance criteria.

When I run Psalm on a plugin I get (among other errors):

![image](https://user-images.githubusercontent.com/812192/41500727-6a575d20-7165-11e8-8846-21512839b947.png)

Looking through the Psalm documentation, the only thing I can find about fixing these is to create my own stub file? Well it actually says [to use PhpStorm stub files](https://github.com/JetBrains/phpstorm-stubs) but there's no such directory for WordPress.  The way PhpStorm works is that it asks where WordPress is located, and uses that for analysis; without going to town on WordPress itself.

![image](https://user-images.githubusercontent.com/812192/41500807-83599120-7166-11e8-9a8a-1ae2da5da13f.png)

I found this repo and was hoping it could help analyse plugins but it seems to be a config to just check WordPress itself?

Can you point me in the right direction?

**Comment by muglug** [comment]
Hmm. Well it looks like PHPStorm has specific handling for WordPress that Psalm does not.

Psalm's WordPress handling is just "if your files reference the WordPress files, they'll be part of Psalm's analysis".

So if your script has `require_once("path_to_wordpress/wp-load.php")` inside it somewhere, Psalm should know everything it needs to.

But it'll also be pretty slow, because it'll be analysing all the contents of those files too.

Psalm could also generate stub files for a particular package given its components - if you think that'd be useful, feel free to ticket in Psalm's repo.

**Comment by dac514** [comment]
Done.

https://github.com/vimeo/psalm/issues/827

Thanks for the reply.
